### ISSUE TITLE
Python Program to check Armstrong Number

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#12]

**Comment by Rohit-R2000** [comment]
please assign this to me

**Comment by PrajwalGKale** [comment]
## Greetings, @praveensingh212223 
>**I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *Python Programming* . and love to do it.**

**Comment by MadhukeshSingh** [comment]
please merge PR #16

**Comment by akashbiswas0** [comment]
@praveensingh212223 pls assign it to me

**Comment by kashyap-ji** [comment]
hey @praveensingh212223 i have the python code ready for this. Can you assign this to me

**Comment by sangalgovind** [comment]
@praveensingh212223 plz assign it to me

**Comment by MrJayendra** [comment]
I am interested in this work.
PLEASE assign it to me.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?

**Comment by tanyaa-arora** [comment]
@praveensingh212223 I'd like to work on this issue
