### ISSUE TITLE
Python program to convert Celsius to Fahrenheit

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#13]

**Comment by dNhunter3107** [comment]
I would like to do this task. Please assign me.

**Comment by akhilender-bongirwar** [comment]
Hi @praveensingh212223, I would like to contribute. Please assign me this.

**Comment by MadhukeshSingh** [comment]
Please Merge PR #17 for hacktoberfest

**Comment by sangalgovind** [comment]
@praveensingh212223 plz assign it to me

**Comment by darkbits018** [comment]
Assign to me please

**Comment by md-tausif09** [comment]
please assign me

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?
