### ISSUE TITLE
create a simple calculator

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#2]
create a simple calculator in python or javascript. #hacktoberfest

**Comment by syprogrammer** [comment]
can you assign me

**Comment by Aditii-Gupta** [comment]
I can create a simple calculator using javascript.

**Comment by praveensingh212223** [comment]
Syprogrammer:- Please Create the file in “Python format “

Aditi:- Please Create the file in javascript and push a folder including your script “javascript_scripts”

**Comment by syprogrammer** [comment]
can i make a calculator website using javascript

**Comment by praveensingh212223** [comment]
Sure!
