### ISSUE TITLE
Create a python program to check weather a number is palindrome number or not

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#40]

**Comment by sujal-goswami** [comment]
Hey @praveensingh212223  I want to work on this can you assign this to me

**Comment by Subhajit767** [comment]
I want to work on this so please assign this to me

**Comment by akashbiswas0** [comment]
@praveensingh212223 pls assign it to me

**Comment by NotAtitYet** [comment]
Please assign this to me.

**Comment by Kaushals112** [comment]
please assign this task to me
