### ISSUE TITLE
Create a script to check weather Number is Positive, Negative or Zero

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#5]
create a python program to check if a number is positive, negative or zero

**Comment by Tarun-k-Gupta** [comment]
I want to work on this issue. Please assign this to me.

**Comment by praveensingh212223** [comment]
make sure to star the repo! Thank you

**Comment by Tarun-k-Gupta** [comment]
Created the pull request.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?
