### ISSUE TITLE
create a python program to find the area of a triangle

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#6]
python program to find the area of a triangle

**Comment by sujal-goswami** [comment]
@praveensingh212223  assign this to me i want to work on this

**Comment by Ashpreet-Singh** [comment]
Hey @praveensingh212223 can I do this

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?
