### ISSUE TITLE
create a python program to check Leap Year

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#7]
create a python program to check leap year

**Comment by sujal-goswami** [comment]
@praveensingh212223  i want to work on this assign this to me

**Comment by praveensingh212223** [comment]
assigned! Happy coding

**Comment by Ashpreet-Singh** [comment]
Hey @praveensingh212223 can I do this

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?
