### ISSUE TITLE
Python Program to Display Fibonacci Sequence Using Recursion

### ISSUE THREAD

**Issue by praveensingh212223** [praveensingh212223/hacktoberfest_2022#8]

**Comment by Rohit-R2000** [comment]
sir please assign this issue to me

**Comment by PrajwalGKale** [comment]
## Greetings, @praveensingh212223
> **I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *Python Programming* . and love to do it.**

**Comment by MadhukeshSingh** [comment]
please accept my PR #18

**Comment by akashbiswas0** [comment]
@praveensingh212223 pls assign it to me

**Comment by sangalgovind** [comment]
@praveensingh212223 plz assign it to me

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?
